In [3]:
""""
Dependiendo de sus dimensiones, se llaman: 1 escalar, 2 Matriz, D>=3 Tensor
"""
import numpy as np

In [5]:
scalar = np.array(42)
scalar.ndim

0

In [6]:
vector = np.array([42,43])
vector.ndim

1

In [8]:
matriz = np.array([[42,43],[44,45]])
matriz.ndim

2

In [9]:
tensor = np.array([[[42,43],[44,45]],[[46,47],[48,49]]])
tensor.ndim

3

## Insertar o eliminar dimensiones.

In [10]:
# Sumar dimensiones seteando un mínimo.
vector = np.array([1,2,3],ndmin=10)
vector

array([[[[[[[[[[1, 2, 3]]]]]]]]]])

In [17]:
# Expandir una dimensión en axis = 0 (COLUMNAS) o 1 (FILAS)
expand = np.expand_dims(np.array([1,2,3]),axis=0)
expand

array([[1, 2, 3]])

In [18]:
print(vector,vector.ndim)
# Reducir la dimensionalidad de mis tensores con numPy.
vector_2 = np.squeeze(vector)
print(vector_2,vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1
