In [10]:
import numpy as np

In [11]:
arr = np.random.randint(1,10,(3,2))

In [12]:
arr.shape # Me dice cuantas filas y columnas tengo.

(3, 2)

In [17]:
arr

array([[1, 5],
       [6, 8],
       [2, 6]])

In [20]:
arr.reshape(2,3)

array([[1, 5, 6],
       [8, 2, 6]])

In [23]:
np.reshape(arr,(2,3))

array([[1, 5, 6],
       [8, 2, 6]])

In [24]:
np.reshape(arr,(2,3),'C') #C

array([[1, 5, 6],
       [8, 2, 6]])

In [25]:
np.reshape(arr,(2,3),'F') #Fortran

array([[1, 2, 8],
       [6, 5, 6]])

In [26]:
np.reshape(arr,(2,3),'A') #Mejor optimizado en tu maquina. Se prefiere usar C

array([[1, 5, 6],
       [8, 2, 6]])