In [8]:
import numpy as np

In [9]:
arr = np.random.randint(1,20,10)

In [10]:
matriz = arr.reshape(2,5)
matriz

array([[ 6, 13, 18,  8,  7],
       [16,  6, 14, 12, 13]])

In [11]:
arr

array([ 6, 13, 18,  8,  7, 16,  6, 14, 12, 13])

In [12]:
arr.max()

18

In [15]:
matriz

array([[ 6, 13, 18,  8,  7],
       [16,  6, 14, 12, 13]])

In [16]:
matriz.max(1) # solo por el eje 1.

array([18, 16])

In [17]:
matriz.max(0) # solo por el eje 0.

array([16, 13, 18, 12, 13])

In [18]:
arr.argmax() # indice donde se encuentra el valor maximo.

2

In [19]:
arr.min()

6

In [20]:
arr.ptp() #peak to peak (MAX - MIN)

12

In [22]:
matriz.ptp(0) #eje 0

array([10,  7,  4,  4,  6])

In [24]:
np.percentile(arr,50) #Valor que se encuentra en la mitad.

12.5

In [27]:
arr.sort()
arr

array([ 6,  6,  7,  8, 12, 13, 13, 14, 16, 18])

In [28]:
np.median(arr)

12.5

In [31]:
np.median(matriz,0) # Mediana por el eje 0

array([ 9.5,  9.5, 10.5, 12. , 15. ])

In [33]:
np.std(arr) # Desviacion estandar

4.075536774462966

In [34]:
np.var(arr) # Varianza

16.61

In [36]:
np.mean(arr) # Media

11.3

In [48]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])
b =np.expand_dims(b, axis=0)

In [51]:
np.concatenate((a,b),axis=0) # para ser concatenadas deben tener la misma direccion
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [50]:
b.T #transpuesta de una matriz

array([[5],
       [6]])