In [2]:
import numpy as np

In [3]:
lista = [1,2]
lista

[1, 2]

In [4]:
lista*2

[1, 2, 1, 2]

In [5]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr2 = arr.copy()
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr2*2
arr**2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])